# -*- coding: utf-8 -*-
"""ShreeShukla2401920140170.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjsQqfrVD1LhIs43RnCQjg0sgd2Gw4Aq
"""

print("Hello World")

print("AI Bootcamp")

print("8+19=27")

print("I am Shree")
print(8+9)
z=0
print("z",z)

